### ISSUE TITLE
[Agency] Avoid custom http status code

### ISSUE THREAD

**Issue by HenriJ** [CityOfLosAngeles/mobility-data-specification#127] opened 2018-10-08 13:13 UTC
The current version of the specification (https://github.com/CityOfLosAngeles/mobility-data-specification/blob/e2faabf5a7e59f4ec4422a1e0c8c4e66361547cc/agency/README.md) is not very clear about what the structure of the response body should be in case of an error.
It looks like the "message" enum are http status code ? If it is the case, using custom http status code should be avoided (especially using 3xx codes for client errors)

2 examples of good responses body in case of error:
* How Oauth2 does it: https://tools.ietf.org/html/rfc6749 `{ "error": "my_error_code", "error_description": "human readable message" }`
* How a Kafka subsystem does it (add 2 digits to http status codes): https://github.com/confluentinc/kafka-rest/blob/master/docs/api.rst#errors `{"error_code": "40401", "message": "human readable message"}`

**Comment by oderby** [comment] 2018-10-09 04:07
Dupe of #105

**Comment by hunterowens** [comment] 2018-10-15 19:46
closing as dupe. Move to #105

**Closed by hunterowens** 2018-10-15 19:46 UTC
Labels: Agency
